repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace

-   repo: git://github.com/igorshubovych/markdownlint-cli
    sha: v0.5.0
    hooks:
    -   id: markdownlint
