version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build container
          command: docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
                                --build-arg VCS_REF=$CIRCLE_SHA1
                                -t circleci-docker-primary .
      - run:
          name: Release container
          command: |
            docker tag circleci-docker-primary trussworks/circleci-docker-primary:$CIRCLE_SHA1
            docker push trussworks/circleci-docker-primary:$CIRCLE_SHA1
            docker tag circleci-docker-primary trussworks/circleci-docker-primary:$CIRCLE_BRANCH
            docker push trussworks/circleci-docker-primary:$CIRCLE_BRANCH
            # push default tag ("latest") if we're on master
            if [[ $CIRCLE_BRANCH = master ]]; then
              docker tag circleci-docker-primary trussworks/circleci-docker-primary
              docker push trussworks/circleci-docker-primary
            fi
